# Generated by Django 5.1.1 on 2024-10-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('special_status', 'User can see all available courses')]},
        ),
    ]
