# Generated by Django 5.1.1 on 2024-10-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('special_status', 'User can access all courses')]},
        ),
    ]
